name: latest and stable dist-tag parity
on:
  registry_package:
    types: [published, updated]

# Every time a package is published to this repo:
#   1. Get the 'latest' version number
#   2. If the package that was just published is the same as 'latest'
#      then we set the dist tag for that package to also be 'stable'
jobs:
  set-tag:
    name: Set 'latest' block to be tagged as 'stable'
    if: startsWith(github.event.package.version, '0.0.0') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
      - id: latestversion
        run: echo "::set-output name=latest::$(npm view ${{ github.event.package.name }} dist-tags.latest)"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ github.event.package.name }}@${{ github.event.package.version }}
      - if: github.event.package.version == steps.latestversion.outputs.latest
        run: npm dist-tag add ${{ github.event.package.name }}@${{ steps.latestversion.outputs.latest }} stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
