name: stable-mentor blocks publish to stable-mentor tag
on:
  push:
    branches:
      - stable-mentor

# Publishes stable-mentor builds with the dist tag of "stable-mentor" and
# with a version of 0.0.0 with a short git SHA appended to
# the end.
jobs:
  publish:
    name: stable-mentor block publish
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Cache NPM files
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: Publish to stable-mentor tag with a short git SHA as the version
        run: npx lerna publish 0.0.0-$(git rev-parse --short HEAD) --no-git-tag-version --no-push --dist-tag stable-mentor --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check stable-mentor failure status
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
