name: Test blocks

on:
  push:
    branches:
      - PEN-1339-tests-automation
  # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node with 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: Run tests
        run: npm test
